cache:
    paths:
        - .gradle/
        - gradle-7.2/
        - gradle/
        - gradlew

default:
  interruptible: true
  image: registry.videolan.org/vlc-debian-android:20220224093321
  tags:
    - amd64
    - docker

stages:
  - build

# Rebuilds libvlc JNI
.build-libvlc-base:
    stage: build
    script: |
        rm -rf vlc
        ./buildsystem/get-vlc.sh
        export VLC_CONTRIB_SHA="$(cd vlc && extras/ci/get-contrib-sha.sh android-${ARCH})"
        export VLC_PREBUILT_CONTRIBS_URL="https://artifacts.videolan.org/vlc-3.0/android-${ARCH}/vlc-contrib-${TRIPLET}-${VLC_CONTRIB_SHA}.tar.bz2"
        if vlc/extras/ci/check-url.sh "$VLC_PREBUILT_CONTRIBS_URL"; then CONTRIB_FLAGS="--with-prebuilt-contribs"; fi
        ./buildsystem/compile-libvlc.sh -a ${ARCH} $CONTRIB_FLAGS
    rules:
        # Explicitely refuse to build anything that would also trigger
        # a medialib build
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - buildsystem/**/*
        when: never
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - libvlc/**/*
      - if: '$CI_PIPELINE_SOURCE == "push"'
    variables:
        MAKEFLAGS: -j8

#################################
# Template config instantiation #
#################################

build-libvlc-arm64:
    extends: .build-libvlc-base
    variables:
        ARCH: arm64
        TRIPLET: aarch64-linux-android

build-libvlc-armv7:
    extends: .build-libvlc-base
    variables:
        ARCH: arm
        TRIPLET: arm-linux-androideabi

build-libvlc-x86:
    extends: .build-libvlc-base
    variables:
        ARCH: x86
        TRIPLET: i686-linux-android

build-libvlc-x86_64:
    extends: .build-libvlc-base
    variables:
        ARCH: x86_64
        TRIPLET: x86_64-linux-android

#
.build-release-libs-base:
    rules:
      - if: '$CI_COMMIT_TAG =~ /^libvlc-.*$/'
    variables:
      M2_REPO: "$CI_PROJECT_DIR/aars/repository"

